#!/usr/bin/python3

"""
Dependencies
sudo apt install python3-rpi.gpio

"""
import time
import RPi.GPIO as GPIO

# setup BCM pin GPIO17 which is physical pin 11
GPIO.setmode(GPIO.BCM)
GPIO.setwarnings(False)
GPIO.setup(17, GPIO.OUT)
pwm = GPIO.PWM(17, 100)

# start the pwm output
pwm.start(0)

# step through the brightness levels 0 - 100 then exit
count = 0
while count < 100:
	# increment count by 1
	count += 1
	pwm.ChangeDutyCycle(count)
	time.sleep(1)

# end the pwm
pwm.stop()
